"""Inspection workflow for arbitrary time-series inputs."""

from __future__ import annotations

from typing import Any, List, Optional

import numpy as np

from ts_agents.cli.input_parsing import SeriesInput
from ts_agents.cli.output import to_jsonable
from ts_agents.contracts import ToolPayload

from .common import ensure_output_dir, write_json_artifact, write_plot_artifact, write_text_artifact


def run_inspect_series_workflow(
    series_input: SeriesInput,
    *,
    output_dir: str,
    max_lag: Optional[int] = None,
    skip_plots: bool = False,
) -> ToolPayload:
    """Run a lightweight diagnostics workflow on an arbitrary series."""
    from ts_agents.core.spectral import detect_periodicity
    from ts_agents.core.statistics import compute_autocorrelation, describe_series

    workflow_name = "inspect-series"
    output_path = ensure_output_dir(output_dir)
    stats = describe_series(series_input.series, extended=True)
    periodicity = detect_periodicity(series_input.series, top_n=3)

    resolved_max_lag = max_lag if max_lag is not None else min(64, max(8, len(series_input.series) // 4))
    acf = compute_autocorrelation(series_input.series, max_lag=resolved_max_lag)

    recommended_next_steps = _recommend_next_steps(
        periodicity=periodicity,
        acf=acf,
        length=len(series_input.series),
    )
    effective_max_lag = max(len(acf) - 1, 0)
    summary_data = {
        "workflow": workflow_name,
        "source": series_input.provenance.get("series_ref", {}),
        "series_length": int(len(series_input.series)),
        "stats": to_jsonable(stats),
        "periodicity": to_jsonable(periodicity),
        "autocorrelation": {
            "max_lag": int(effective_max_lag),
            "requested_max_lag": int(resolved_max_lag),
            "lag_1": float(acf[1]) if len(acf) > 1 else None,
        },
        "recommended_next_steps": recommended_next_steps,
        "output_dir": str(output_path),
    }

    artifacts = [
        write_json_artifact(
            data=summary_data,
            path=output_path / "summary.json",
            description="Inspection summary JSON.",
            created_by=workflow_name,
        )
    ]
    warnings: List[str] = []

    if not skip_plots:
        try:
            import matplotlib.pyplot as plt

            fig, ax = plt.subplots(figsize=(10, 6))
            ax.bar(np.arange(len(acf)), acf)
            ax.set_title("Autocorrelation")
            ax.set_xlabel("Lag")
            ax.set_ylabel("Correlation")
            fig.tight_layout()
            artifacts.append(
                write_plot_artifact(
                    figure=fig,
                    path=output_path / "autocorrelation.png",
                    description="Autocorrelation plot generated by the inspect-series workflow.",
                    created_by=workflow_name,
                )
            )
            plt.close(fig)
        except ImportError:
            warnings.append("matplotlib is not installed; skipping autocorrelation plot.")

    report = _build_report(
        series_input=series_input,
        stats=to_jsonable(stats),
        periodicity=to_jsonable(periodicity),
        recommended_next_steps=recommended_next_steps,
    )
    artifacts.append(
        write_text_artifact(
            content=report,
            path=output_path / "report.md",
            description="Inspection workflow markdown report.",
            created_by=workflow_name,
        )
    )

    dominant_period = summary_data["periodicity"].get("dominant_period")
    lag_one = summary_data["autocorrelation"].get("lag_1")
    summary = (
        f"Inspect-series workflow completed for {series_input.label}. "
        f"Dominant period: {_format_number(dominant_period)}; "
        f"lag-1 autocorrelation: {_format_number(lag_one)}."
    )
    return ToolPayload(
        kind="workflow",
        summary=summary,
        status="degraded" if warnings else "ok",
        data=summary_data,
        artifacts=artifacts,
        warnings=warnings,
        provenance=series_input.provenance,
    )


def _recommend_next_steps(
    *,
    periodicity: Any,
    acf: np.ndarray,
    length: int,
) -> List[str]:
    steps: List[str] = []
    if getattr(periodicity, "confidence", 0.0) >= 0.2 and getattr(periodicity, "dominant_period", 0.0) > 1:
        steps.append(
            f"Run forecast-series with a horizon aligned to the detected period (~{periodicity.dominant_period:.1f})."
        )
    if len(acf) > 1 and abs(float(acf[1])) >= 0.5:
        steps.append("Inspect decomposition or changepoints because the series shows strong short-lag dependence.")
    if length < 64:
        steps.append("Treat periodicity findings as low-confidence because the series is short.")
    if not steps:
        steps.append("Use forecast-series as the next baseline workflow if forecasting is the downstream task.")
    return steps


def _build_report(
    *,
    series_input: SeriesInput,
    stats: dict[str, Any],
    periodicity: dict[str, Any],
    recommended_next_steps: List[str],
) -> str:
    top_periods = periodicity.get("top_periods") or []
    next_steps_lines = [f"- {step}" for step in recommended_next_steps]
    return "\n".join(
        [
            "### Report on Inspect-Series Workflow",
            "",
            f"- **Source**: `{series_input.label}`",
            f"- **Length**: {stats.get('length')}",
            f"- **Mean**: {_format_number(stats.get('mean'))}",
            f"- **Std**: {_format_number(stats.get('std'))}",
            f"- **Min / Max**: {_format_number(stats.get('min'))} / {_format_number(stats.get('max'))}",
            f"- **Dominant Period**: {_format_number(periodicity.get('dominant_period'))}",
            f"- **Periodicity Confidence**: {_format_number(periodicity.get('confidence'))}",
            f"- **Top Periods**: {', '.join(_format_number(value) for value in top_periods) if top_periods else 'n/a'}",
            "",
            "#### Recommended Next Steps",
            *next_steps_lines,
        ]
    )


def _format_number(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, (int, float)):
        return f"{value:.4f}"
    return str(value)
